Executes on what we compile; if we break the opcode:
```
thread 'main' panicked at risc0/r0vm/src/lib.rs:195:56:
called `Result::unwrap()` on an `Err` value: witness generation failure

Caused by:
    [6319]: eqz failure at: MemoryWrite(zirgen/circuit/rv32im/v2/dsl/mem.zir:99)
```